"""Verified Snapshot, Scope authoring, and recursive LessonIR contracts."""

from .annotated_teaching import (
    ANNOTATED_TEACHING_PLAN_CONTRACT,
    AnnotatedTeachingPlan,
    AnnotatedTeachingPlanProjector,
    AnnotatedTeachingProjection,
    AnnotatedTeachingProjectionError,
    AnnotatedTeachingPrompt,
    TeachingMaterialProjector,
    annotated_teaching_plan_schema,
    build_projection_audit,
    lesson_scope_content_schema,
    render_annotated_teaching_prompt,
)
from .lesson_ir import (
    LESSON_ASSEMBLY_AUTHORITY_CONTRACT,
    LESSON_IR_CONTRACT,
    LessonAuthoringPipeline,
    LessonGoal,
    LessonIR,
    LessonIRValidationError,
    LessonScope,
    LessonStep,
    LessonTraversalIndex,
    OwnedLessonStep,
    RecursiveLessonBuildResult,
    RecursiveLessonIRAssembler,
    RecursiveLessonIRValidator,
    lesson_ir_from_payload,
)
from .models import (
    EXPLANATION_SNAPSHOT_CONTRACT,
    ExplanationSnapshot,
    TeachingGoal,
    TeachingScope,
    TeachingSource,
    explanation_snapshot_from_payload,
)
from .snapshot import ExplanationSnapshotBuilder
from .scope_lesson import (
    BoundLessonStep,
    LessonScopeContentValidator,
    ScopeLessonAuthoringService,
    ScopeLessonConfigurationError,
    ScopeLessonDiagnostic,
    ScopeLessonGenerationResult,
    ScopeLessonValidationResult,
    build_deterministic_scope_content,
    evaluate_scope_lesson_content,
)

__all__ = [
    "ANNOTATED_TEACHING_PLAN_CONTRACT",
    "AnnotatedTeachingPlan",
    "AnnotatedTeachingPlanProjector",
    "AnnotatedTeachingProjection",
    "AnnotatedTeachingProjectionError",
    "AnnotatedTeachingPrompt",
    "BoundLessonStep",
    "EXPLANATION_SNAPSHOT_CONTRACT",
    "ExplanationSnapshot",
    "ExplanationSnapshotBuilder",
    "LESSON_ASSEMBLY_AUTHORITY_CONTRACT",
    "LESSON_IR_CONTRACT",
    "LessonAuthoringPipeline",
    "LessonGoal",
    "LessonIR",
    "LessonIRValidationError",
    "LessonScope",
    "LessonScopeContentValidator",
    "LessonStep",
    "LessonTraversalIndex",
    "OwnedLessonStep",
    "RecursiveLessonBuildResult",
    "RecursiveLessonIRAssembler",
    "RecursiveLessonIRValidator",
    "TeachingGoal",
    "TeachingMaterialProjector",
    "TeachingScope",
    "TeachingSource",
    "ScopeLessonAuthoringService",
    "ScopeLessonConfigurationError",
    "ScopeLessonDiagnostic",
    "ScopeLessonGenerationResult",
    "ScopeLessonValidationResult",
    "annotated_teaching_plan_schema",
    "build_projection_audit",
    "build_deterministic_scope_content",
    "evaluate_scope_lesson_content",
    "explanation_snapshot_from_payload",
    "lesson_scope_content_schema",
    "lesson_ir_from_payload",
    "render_annotated_teaching_prompt",
]
