"""加权二次函数路径最值 SolverFamilySpec。

这里描述的是河西 25 所代表的“二次函数 + 加权路径最值”题型上下文。它只用于
RuntimeOrchestrator 匹配 family，并给 Planner 提供题型级参考，不保存具体答案。
"""

from __future__ import annotations

from shuxueshuo_server.solver.family.models import (
    CapabilityContractSpec,
    ConditionPattern,
    FamilyMatchRule,
    FamilyRuntimePreflightSpec,
    FamilySourceRequirementSpec,
    MethodBindingRuleSpec,
    MacroSearchSpec,
    RecipeExecutionSpec,
    recipe_output_alias,
    SolverFamilySpec,
    StateSlotPattern,
    StepRecipeSpec,
    expand_family_spec,
)
from shuxueshuo_server.solver.family.capability_packs import (
    DEFAULT_CAPABILITY_PACK_REGISTRY,
)
from shuxueshuo_server.solver.family.common_binding_rules import (
    condition_arg_binding,
    entity_identity_binding,
    exact_call_result_binding,
    latest_state_binding,
    parameter_basis_binding,
    previous_output_identity_binding,
    public_arg_binding,
    related_condition_binding,
    source_object_identity_binding,
)
_QUADRATIC_WEIGHTED_PATH_MINIMUM_FAMILY = SolverFamilySpec(
    family_id="QuadraticWeightedPathMinimumSolver",
    match=FamilyMatchRule(
        patterns=("weighted-path-minimum",),
        problem_types=("quadratic_weighted_path_minimum",),
    ),
    title="二次函数加权路径最值",
    description=(
        "目标中存在非1距离权重，需要先用比例或辅助直角三角形把加权项转换为"
        "可拉直路径的二次函数最值题。"
    ),
    use_when=(
        "题面目标明确形如 k*PA+PB，且 k 不等于1；该权重是最值目标的一部分，"
        "需要加权几何变换后才能使用最短路径。"
    ),
    required_source_requirements=(
        FamilySourceRequirementSpec(
            "entity_type",
            ("function",),
            "题面必须声明至少一个二次函数对象。",
        ),
        FamilySourceRequirementSpec(
            "fact_type",
            ("path_minimum_target",),
            (
                "必须用 path_minimum_target 声明完整带权路径；sibling 比例事实不可替代。"
            ),
        ),
        FamilySourceRequirementSpec(
            "fact_type",
            ("minimum_value",),
            "题面必须直接提出或给出路径最小值。",
        ),
    ),
    runtime_preflights=(
        FamilyRuntimePreflightSpec(
            method_id="weighted_axis_path_triangle_transform",
            trigger_fact_types=("minimum_value",),
            trigger_selector_id="weighted_path_minimum",
            required_fact_types=("path_minimum_target",),
            source_trigger_fact_types=("minimum_value_given",),
            source_required_fact_types=("minimum_target",),
            source_input_names=(
                "condition",
                "fixed_point",
                "moving_point",
                "dynamic_parameter",
            ),
            description=(
                "每个 minimum_value scope 须试运行加权转化；所需 Point 须有"
                " coordinate；仅有点名或描述不能代替已计算坐标。"
            ),
        ),
    ),
    do_not_use_when=(
        "系数只出现在函数、方程或普通线段比例中，而不是路径目标的权重。",
        "目标只是两个无权距离之和，即使题面另有直角或等长关系。",
        "核心机制是射线等长替换或正方形反射。",
    ),
    common_goal_types=(
        "derive_parabola",
        "derive_vertex_point",
        "derive_constructed_point",
        "derive_weighted_path_minimum",
        "derive_parameter",
    ),
    strategy_principles=(
        "先将每一问的已知系数与已知曲线点尽量代入，得到当前问最简抛物线表达式。",
        "函数化简只有在能显著减少未知量时才单独成步：理想状态是 a、b、c 完全确定，或只剩一个后续条件会直接求解/引用的未知量；若 b、c 等多个参数都能表达同一函数，应结合后续曲线点、几何筛选、最值或答案目标选择保留哪个参数。",
        "几何构造点先列候选；若候选点还需落在含参曲线上，再用候选曲线点求参 recipe 筛选并反求参数。",
        "加权路径最值优先寻找几何转化：用辅助直角三角形把加权段转成同倍率折线，再用折线拉直或等价最短路径处理。",
        "加权路径最值按可执行颗粒拆成：weighted_axis_path_triangle_transform 做几何转化，linked_broken_path_minimum_expression 求最小值表达式，parameter_from_expression_value 由给定值反求参数；不要把三步合成一个 utility step。",
    ),
    base_packs=(
        "quadratic_core",
        "parameter_solving_core",
        "coordinate_geometry_core",
    ),
    mechanism_packs=(
        "right_angle_equal_length_core",
        "weighted_path_transform_core",
    ),
    method_ids=(
        "quadratic_from_constraints",
        "quadratic_vertex_point",
        "quadratic_y_axis_intercept_point",
        "quadratic_x_axis_intercept_point",
        "right_angle_equal_length_candidates",
        "filter_point_candidates_by_quadratic_curve",
        "parameter_from_curve_point_on_quadratic",
        "point_on_parabola_at_x",
        "evaluate_expression_at_parameter",
        "parameter_from_segment_length",
        "weighted_axis_path_triangle_transform",
        "linked_broken_path_minimum_expression",
        "parameter_from_expression_value",
    ),
    step_recipes=(
        StepRecipeSpec(
            recipe_id="curve_candidate_parameter_solve",
            goal_type="derive_constructed_point",
            title="曲线候选点筛选并反求参数",
            description=(
                "前序几何构造已经产生一组有坐标的候选点后，用当前问含参抛物线"
                "和参数约束筛出唯一候选点，再把该含参点代入抛物线反求参数并"
                "代回抛物线。candidates 必须引用前序调用实际产出的候选点集合，"
                "不能把尚未求出坐标的目标点包成单元素伪候选列表。若曲线条件"
                "本身不能唯一排除分支时，runtime 会按残余符号自动绑定唯一可见的 "
                "symbol_constraint；只有存在多个非等价候选时才需要显式消歧。"
            ),
            method_ids=(
                "filter_point_candidates_by_quadratic_curve",
                "parameter_from_curve_point_on_quadratic",
            ),
            execution=RecipeExecutionSpec(
                recipe_id="curve_candidate_parameter_solve",
                method_sequence=(
                    "filter_point_candidates_by_quadratic_curve",
                    "parameter_from_curve_point_on_quadratic",
                ),
                execution_mode="direct",
                execution_strategy="curve_candidate_parameter_solve",
                intermediate_wiring=(
                    ("filter_point_candidates_by_quadratic_curve.selected_candidate", "parameter_from_curve_point_on_quadratic.point"),
                ),
                input_aliases=(
                    (
                        "candidates",
                        "filter_point_candidates_by_quadratic_curve.candidates",
                    ),
                    (
                        "parabola",
                        "filter_point_candidates_by_quadratic_curve.parabola",
                    ),
                    (
                        "parabola",
                        "parameter_from_curve_point_on_quadratic.quadratic",
                    ),
                    (
                        "target_point",
                        "filter_point_candidates_by_quadratic_curve.target",
                    ),
                    (
                        "symbol_constraint",
                        "filter_point_candidates_by_quadratic_curve.parameter_constraint",
                    ),
                    (
                        "symbol_constraint",
                        "parameter_from_curve_point_on_quadratic.parameter_constraint",
                    ),
                ),
                strategy_input_targets=(
                    "filter_point_candidates_by_quadratic_curve.x",
                    "filter_point_candidates_by_quadratic_curve.parameter",
                    "parameter_from_curve_point_on_quadratic.x",
                    "parameter_from_curve_point_on_quadratic.parameter",
                ),
                output_aliases=(
                    recipe_output_alias(
                        "parameter_from_curve_point_on_quadratic.point",
                        "Point",
                        "selected_curve_point",
                        identity_policy="target_object",
                    ),
                    recipe_output_alias(
                        "parameter_from_curve_point_on_quadratic.parameter_value",
                        "ParameterValue",
                        "parameter_value",
                        required=False,
                        cardinality="optional",
                    ),
                    recipe_output_alias(
                        "parameter_from_curve_point_on_quadratic.parabola",
                        "Parabola",
                        "solved_parabola",
                        required=False,
                        cardinality="optional",
                        identity_policy="preserve_input_object",
                        identity_arg="parabola",
                        write_mode="transition",
                    ),
                ),
            ),
            do_not_use_when=(
                "目标点已经在题面结构化声明横坐标，只需代入抛物线求纵坐标。",
                "当前没有前序几何构造产生的 materialized PointList 候选状态。",
                "试图把尚未求坐标的 target_point 本身或只含该对象的列表作为 candidates。",
                (
                    "多个候选都可能满足曲线方程，但没有提供用于选择分支的参数"
                    "范围或符号约束；不要假定默认旋转方向。"
                ),
            ),
        ),
    ),
    capability_contracts=(
        CapabilityContractSpec(
            capability_id="curve_candidate_parameter_solve",
            kind="recipe",
            slot_reads=(
                StateSlotPattern(
                    "candidate",
                    "PointList",
                    object_kind="point",
                    semantic_role="candidates",
                    description=(
                        "前序几何构造调用实际产出的候选点列表；每个候选都必须已有"
                        "坐标状态。不能填写尚未求出坐标的目标点，也不能填写只含目标对象的"
                        "伪候选列表。"
                    ),
                ),
                StateSlotPattern(
                    "expression",
                    "Parabola",
                    object_kind="function",
                    semantic_role="parabola",
                    description="用于检验候选点并反求参数的当前含参抛物线状态。",
                ),
                StateSlotPattern(
                    "coordinate",
                    "Point",
                    object_kind="point",
                    semantic_role="target_point",
                    semantic_ref_role="object_identity",
                    description=(
                        "候选筛选后要写入坐标的题面目标点身份；它不是 candidates "
                        "的替代输入。"
                    ),
                ),
            ),
            condition_reads=(
                ConditionPattern(
                    "point_on_curve",
                    required=False,
                    description="目标点属于该抛物线的结构化条件。",
                ),
                ConditionPattern(
                    "symbol_constraint",
                    required=False,
                    deterministic_resolver="unique_related_state",
                    description=(
                        "用于排除候选分支的参数范围或符号约束。runtime 会按"
                        "曲线残余符号自动绑定唯一可见约束；仅在多个非等价"
                        "约束都可用时填写此参数进行消歧。"
                    ),
                ),
            ),
            slot_writes=(
                StateSlotPattern(
                    "coordinate",
                    "Point",
                    object_kind="point",
                    semantic_role="selected_curve_point",
                    output_key="parameter_from_curve_point_on_quadratic.point",
                    write_mode="create",
                    description=(
                        "从前序 PointList 中筛出的唯一候选点，并保持 target_point "
                        "的对象身份。"
                    ),
                ),
            ),
        ),
    ),
    method_binding_rules=(
        MethodBindingRuleSpec(
            method_id="right_angle_equal_length_candidates",
            input_bindings=(
                latest_state_binding("anchor"),
                latest_state_binding("reference"),
                public_arg_binding("target"),
            ),
        ),
        MethodBindingRuleSpec(
            method_id="parameter_from_segment_length",
            input_bindings=(
                public_arg_binding("p1"),
                public_arg_binding("p2"),
                public_arg_binding("reference_p1", required=False),
                public_arg_binding("reference_p2", required=False),
                parameter_basis_binding(
                    (
                        "p1",
                        "p2",
                        "reference_p1",
                        "reference_p2",
                        "condition",
                        "constraint",
                    )
                ),
                condition_arg_binding("condition", public_arg="length_squared"),
                related_condition_binding(
                    "constraint",
                    condition_kinds=("symbol_constraint",),
                    related_args=("parameter",),
                    required=False,
                ),
            ),
        ),
        MethodBindingRuleSpec(
            method_id="weighted_axis_path_triangle_transform",
            input_bindings=(
                condition_arg_binding("condition", public_arg="minimum_value"),
                public_arg_binding("fixed_point"),
                public_arg_binding("moving_point"),
                source_object_identity_binding(
                    "moving_point",
                    input_name="moving_point_ref",
                    required=True,
                ),
                entity_identity_binding("linked_fixed_endpoint_ref"),
                parameter_basis_binding(
                    ("moving_point", "condition"),
                    input_name="dynamic_parameter",
                ),
                previous_output_identity_binding(
                    "auxiliary_point_ref",
                    output_name="auxiliary_point",
                ),
            ),
        ),
        MethodBindingRuleSpec(
            method_id="linked_broken_path_minimum_expression",
            input_bindings=(
                exact_call_result_binding("path_transformation"),
                exact_call_result_binding("auxiliary_locus"),
                public_arg_binding("fixed_point"),
                public_arg_binding("curve_point"),
                public_arg_binding("moving_point"),
                public_arg_binding("auxiliary_point"),
                parameter_basis_binding(
                    ("curve_point",),
                    input_name="parameter",
                ),
                parameter_basis_binding(
                    ("moving_point", "dynamic_constraint"),
                    input_name="dynamic_parameter",
                ),
                related_condition_binding(
                    "parameter_constraint",
                    condition_kinds=("symbol_constraint",),
                    related_args=("parameter",),
                ),
                condition_arg_binding("dynamic_constraint"),
            ),
        ),
    ),
)

QUADRATIC_WEIGHTED_PATH_MINIMUM_FAMILY = expand_family_spec(
    _QUADRATIC_WEIGHTED_PATH_MINIMUM_FAMILY,
    DEFAULT_CAPABILITY_PACK_REGISTRY,
)
