"""二次函数路径最值 SolverFamilySpec。

这里抽取的是“二次函数 + 构造点 + 路径最值”这类题的共性上下文，供后续通用
Planner 参考。它不包含南开 25 的固定 StepPlan，也不包含最终答案结构。
"""

from __future__ import annotations

from shuxueshuo_server.solver.contracts import (
    LegacyExpansionSelectorSpec,
    LegacySelectorInputBindingSpec,
)
from shuxueshuo_server.solver.family.models import (
    FamilyMatchRule,
    FamilySourceRequirementSpec,
    MethodCompanionOutputSpec,
    MethodBindingRuleSpec,
    MacroSearchSpec,
    RecipeExecutionSpec,
    recipe_output_alias,
    SolverFamilySpec,
    StateObjectRoleProjectionSpec,
    StepRecipeSpec,
    expand_family_spec,
)
from shuxueshuo_server.solver.family.capability_packs import (
    BROKEN_PATH_SELECT_DO_NOT_USE_WHEN,
    DEFAULT_CAPABILITY_PACK_REGISTRY,
    RIGHT_ANGLE_EQUAL_LENGTH_DO_NOT_USE_WHEN,
    STRAIGHTENED_ENDPOINT_RESULT_FORM,
    STRAIGHTENED_DISTANCE_DO_NOT_USE_WHEN,
    TWO_MOVING_POINTS_PATH_REDUCTION_DESCRIPTION,
    TWO_MOVING_POINTS_REDUCTION_DO_NOT_USE_WHEN,
    TWO_MOVING_PATH_TRANSFORMATION_OBJECT_ROLES,
)


_QUADRATIC_PATH_MINIMUM_FAMILY = SolverFamilySpec(
    family_id="QuadraticPathMinimumSolver",
    match=FamilyMatchRule(
        patterns=("path-minimum",),
        problem_types=("quadratic_path_minimum",),
    ),
    title="普通二次函数路径最值",
    description=(
        "二次函数题中的普通点、线段或折线路径最值；核心机制是不带特殊权重、"
        "射线等长替换或正方形反射的通用路径降维与拉直。"
    ),
    use_when=(
        "题面要求普通距离和或折线路径的最小值，允许出现辅助性的直角、等长或"
        "中点关系，但路径机制本身不依赖非1权重、射线等长构造或正方形反射。"
    ),
    required_source_requirements=(
        FamilySourceRequirementSpec(
            "entity_type",
            ("function",),
            "题面必须声明至少一个二次函数对象。",
        ),
        FamilySourceRequirementSpec(
            "fact_type",
            ("path_minimum_target", "minimum_value"),
            "题面必须显式给出路径/距离最值目标或最小值条件。",
        ),
    ),
    do_not_use_when=(
        "目标路径含明确的非1权重系数，并以加权几何变换为核心。",
        "题面明确声明射线、射线上动点和等长条件，并用它们替换路径。",
        "题面以正方形顶点、中点、中心或对角线关系完成路径降维或反射。",
    ),
    common_goal_types=(
        "derive_parabola",
        "derive_axis_point",
        "derive_constructed_point",
        "derive_parameter",
        "reduce_path_expression",
        "straighten_broken_path",
        "derive_minimum_value",
        "derive_extremal_point",
    ),
    strategy_principles=(
        "先解析题设中的函数、点、关系和参数约束。",
        "每一问进入几何或路径推导前，先尽量代入该问已知系数与已知曲线点，化简当前问函数表达式。",
        "函数化简的目标不是缓存复杂含参式，而是让 a、b、c 完全确定或只剩一个后续条件会用到的未知量；若 b、c 等多个参数都能表达同一函数，应根据后续长度、最值、曲线点或答案目标选择保留哪个参数，无法判断时先等待更多约束。",
        "若构造点坐标未知，先由几何关系生成候选，再用题设约束筛选。",
        "能先确定未知参数时，优先先求参数再代入后续表达式。",
        "每一步优先消去已确定的信息：若当前问条件已能确定参数数值，先求参数再代入；若参数暂不能定值，但代入已知系数、已知点或系数关系能减少未知量，则可以先化简表达式。",
        "路径最值先做路径转化，再做折线拉直或等价最短路径处理。",
        "普通路径最值按阶段独立推导：先把两动点路径降为单动点路径，再选择合适的折线拉直方案，最后根据拉直后的端点距离求最小值表达式。",
        "最短路径对应点通常来自约束轨迹与拉直线段的交点。",
    ),
    base_packs=(
        "quadratic_core",
        "parameter_solving_core",
        "coordinate_geometry_core",
        "broken_path_minimum_core",
    ),
    mechanism_packs=("right_angle_equal_length_core",),
    method_ids=(
        "quadratic_axis_from_relation",
        "quadratic_from_constraints",
        "right_angle_equal_length_candidates",
        "select_point_by_quadrant_constraint",
        "parameter_from_segment_length",
        "midpoint_point",
        "two_moving_points_path_reduction",
        "broken_path_straightening_candidates",
        "select_straightening_candidate",
        "distance_between_points",
        "parameter_from_minimum_value",
        "line_intersection_point",
    ),
    step_recipes=(
        StepRecipeSpec(
            recipe_id="right_angle_equal_length_construct_and_select",
            goal_type="derive_constructed_point",
            title="直角等腰构造并筛选点",
            description=(
                "由直角等腰/旋转关系先列出候选点，再结合象限、参数范围或曲线条件"
                "筛选出符合题设的点。"
            ),
            method_ids=(
                "right_angle_equal_length_candidates",
                "select_point_by_quadrant_constraint",
            ),
            execution=RecipeExecutionSpec(
                recipe_id="right_angle_equal_length_construct_and_select",
                method_sequence=(
                    "right_angle_equal_length_candidates",
                    "select_point_by_quadrant_constraint",
                ),
                execution_mode="direct",
                execution_strategy="right_angle_construct_select",
                strategy_input_targets=(
                    "right_angle_equal_length_candidates.anchor",
                    "right_angle_equal_length_candidates.reference",
                    "right_angle_equal_length_candidates.target",
                    "select_point_by_quadrant_constraint.target",
                    "select_point_by_quadrant_constraint.quadrant",
                    "select_point_by_quadrant_constraint.parameter",
                    "select_point_by_quadrant_constraint.parameter_constraint",
                ),
                intermediate_wiring=(
                    ("right_angle_equal_length_candidates.candidates", "select_point_by_quadrant_constraint.candidates"),
                ),
                output_aliases=(
                    recipe_output_alias(
                        "select_point_by_quadrant_constraint.selected_point",
                        "Point",
                        "selected_target_point",
                        identity_policy="target_object",
                        identity_arg="target",
                    ),
                ),
            ),
            do_not_use_when=RIGHT_ANGLE_EQUAL_LENGTH_DO_NOT_USE_WHEN,
        ),
        StepRecipeSpec(
            recipe_id="two_moving_points_path_reduction",
            goal_type="reduce_path_expression",
            title="两动点路径降维：已有固定点替换",
            description=TWO_MOVING_POINTS_PATH_REDUCTION_DESCRIPTION,
            method_ids=("two_moving_points_path_reduction",),
            execution=RecipeExecutionSpec(
                recipe_id="two_moving_points_path_reduction",
                method_sequence=("two_moving_points_path_reduction",),
                execution_mode="direct",
                execution_strategy="single_method",
                strategy_input_targets=(
                    "two_moving_points_path_reduction.original_path",
                    "two_moving_points_path_reduction.first_moving_membership",
                    "two_moving_points_path_reduction.second_moving_membership",
                    "two_moving_points_path_reduction.binding_relation",
                    "two_moving_points_path_reduction.first_segment_start",
                    "two_moving_points_path_reduction.joint_point",
                    "two_moving_points_path_reduction.second_segment_end",
                ),
                output_aliases=(
                    recipe_output_alias(
                        "two_moving_points_path_reduction.path_transformation",
                        "PathTransformation",
                        "path_transformation",
                        identity_policy="derived_role",
                        write_mode="create",
                        description=(
                            "包含降维后的动点、两个固定端点，以及由题面线段"
                            "归属条件提供的动点轨迹证据；后续路径拉直可据此"
                            "省略 moving_locus。"
                        ),
                        provides_semantic_roles=("moving_locus",),
                        object_role_projections=(
                            TWO_MOVING_PATH_TRANSFORMATION_OBJECT_ROLES
                        ),
                    ),
                ),
            ),
            priority="preferred",
            do_not_use_when=TWO_MOVING_POINTS_REDUCTION_DO_NOT_USE_WHEN,
        ),
        StepRecipeSpec(
            recipe_id="broken_path_straightening_and_select",
            goal_type="straighten_broken_path",
            title="折线拉直并选择方案",
            description=(
                "为单动点折线路径构造拉直候选方案，再选择最方便计算且符合题设"
                "结构的方案；本 recipe 只产出拉直方案，不直接产出最小值表达式。"
            ),
            method_ids=(
                "broken_path_straightening_candidates",
                "select_straightening_candidate",
            ),
            execution=RecipeExecutionSpec(
                recipe_id="broken_path_straightening_and_select",
                method_sequence=(
                    "broken_path_straightening_candidates",
                    "select_straightening_candidate",
                ),
                execution_mode="direct",
                execution_strategy="straightening_candidates_select",
                creates=("point",),
                strategy_input_targets=(
                    "broken_path_straightening_candidates.path_transformation",
                    "broken_path_straightening_candidates.moving_point_membership",
                    "broken_path_straightening_candidates.moving_locus",
                    "broken_path_straightening_candidates.fixed_point_1",
                    "broken_path_straightening_candidates.fixed_point_2",
                    "broken_path_straightening_candidates.line_point_1",
                    "broken_path_straightening_candidates.line_point_2",
                    "select_straightening_candidate.target",
                ),
                intermediate_wiring=(
                    ("broken_path_straightening_candidates.candidates", "select_straightening_candidate.candidates"),
                ),
                output_aliases=(
                    recipe_output_alias(
                        "select_straightening_candidate.selected_candidate",
                        "StraighteningCandidate",
                        "straightened_scheme",
                        goal_evidence_tags=(
                            "path_minimum_witness",
                            "path_minimum_extremal_point",
                        ),
                    ),
                    recipe_output_alias(
                        "select_straightening_candidate.auxiliary_point",
                        "Point",
                        "straightening_auxiliary_point",
                        required=False,
                        cardinality="optional",
                        identity_policy="derived_role",
                        goal_evidence_tags=("path_minimum_witness",),
                        equivalent_to="straightened_endpoint_1",
                        description=(
                            "选中候选的反射辅助点，与 straightened_endpoint_1 是同一"
                            "几何状态；不能把二者作为一条直线的两个不同端点。"
                        ),
                    ),
                    recipe_output_alias(
                        "select_straightening_candidate.minimum_point_1",
                        "Point",
                        "straightened_endpoint_1",
                        required=False,
                        cardinality="optional",
                        identity_policy="derived_role",
                        goal_evidence_tags=("path_minimum_witness",),
                        result_form=STRAIGHTENED_ENDPOINT_RESULT_FORM,
                        description=(
                            "拉直后最短等价线段的第一个端点，通常是由反射构造"
                            "得到的辅助点；它不是原路径动点、极值点或答案点。"
                        ),
                        object_role_projections=(
                            StateObjectRoleProjectionSpec(
                                role="moving_object",
                                source_arg="path_transformation",
                                source_object_role="moving_object",
                            ),
                        ),
                    ),
                    recipe_output_alias(
                        "select_straightening_candidate.minimum_point_2",
                        "Point",
                        "straightened_endpoint_2",
                        required=False,
                        cardinality="optional",
                        identity_policy="derived_role",
                        goal_evidence_tags=("path_minimum_witness",),
                        result_form=STRAIGHTENED_ENDPOINT_RESULT_FORM,
                        description=(
                            "拉直后最短等价线段的第二个端点，通常是未被反射的"
                            "另一固定端点；它不是原路径动点、极值点或答案点。"
                        ),
                        object_role_projections=(
                            StateObjectRoleProjectionSpec(
                                role="moving_object",
                                source_arg="path_transformation",
                                source_object_role="moving_object",
                            ),
                        ),
                    ),
                ),
            ),
            priority="preferred",
            do_not_use_when=BROKEN_PATH_SELECT_DO_NOT_USE_WHEN,
        ),
    ),
    method_binding_rules=(
        MethodBindingRuleSpec(
            method_id="quadratic_axis_from_relation",
            input_bindings=(
                LegacySelectorInputBindingSpec("coefficient_relation", "fact:coefficient_relation:Equation"),
                LegacySelectorInputBindingSpec("a", "symbol:a"),
                LegacySelectorInputBindingSpec("b", "symbol:b"),
                LegacySelectorInputBindingSpec("target", "point_output_ref"),
            ),
        ),
        MethodBindingRuleSpec(
            method_id="quadratic_from_constraints",
            input_bindings=(
                LegacySelectorInputBindingSpec("quadratic", "function:parabola"),
                LegacySelectorInputBindingSpec("x", "symbol:x"),
                LegacySelectorInputBindingSpec(
                    "coefficient_relation",
                    "fact:coefficient_relation:Equation",
                    required=False,
                ),
                LegacySelectorInputBindingSpec("all_coefficients", "quadratic_coefficients"),
            ),
            expansion_selectors=(
                LegacyExpansionSelectorSpec("known_coefficients_if_read"),
                LegacyExpansionSelectorSpec("free_quadratic_parameter_if_read"),
                LegacyExpansionSelectorSpec("parameter_value_if_read"),
                LegacyExpansionSelectorSpec("curve_point_if_read"),
                LegacyExpansionSelectorSpec("curve_points_if_parameterized"),
            ),
            always_emit_outputs=("coefficients",),
            companion_outputs=(
                MethodCompanionOutputSpec(
                    "coefficients",
                    "answer_scope_output:coefficients",
                    "runtime_step_output:coefficients",
                ),
            ),
        ),
        MethodBindingRuleSpec(
            method_id="parameter_from_segment_length",
            input_bindings=(
                LegacySelectorInputBindingSpec("p1", "length_segment:p1"),
                LegacySelectorInputBindingSpec("p2", "length_segment:p2"),
                LegacySelectorInputBindingSpec(
                    "parameter",
                    "parameter_symbol",
                    functional_authority="wire",
                    functional_resolver="unique_parameter_symbol",
                ),
                LegacySelectorInputBindingSpec("condition", "fact:length_squared:Condition"),
                LegacySelectorInputBindingSpec("constraint", "parameter_constraint"),
            ),
        ),
        MethodBindingRuleSpec(
            method_id="parameter_from_minimum_value",
            input_bindings=(
                LegacySelectorInputBindingSpec("minimum_expression", "read_type:MinimumExpression"),
                LegacySelectorInputBindingSpec("condition", "fact:minimum_value:Condition"),
                LegacySelectorInputBindingSpec(
                    "parameter",
                    "parameter_symbol",
                    functional_authority="wire",
                    functional_resolver="unique_parameter_symbol",
                ),
                LegacySelectorInputBindingSpec("constraint", "parameter_constraint"),
            ),
        ),
    ),
)

QUADRATIC_PATH_MINIMUM_FAMILY = expand_family_spec(
    _QUADRATIC_PATH_MINIMUM_FAMILY,
    DEFAULT_CAPABILITY_PACK_REGISTRY,
)
